drop sequence SEQ_EM_WQPF_ID;
create sequence SEQ_EM_WQPF_ID
  increment by 1
  start with 1
  maxvalue 1.0E20
  minvalue 1
  NOCYCLE
  NOCACHE
  NOORDER;

drop table IF_EM_WQPF_1;
CREATE TABLE IF_EM_WQPF_1
(
  ID NUMBER(8) NOT NULL
, VEHICLEMODEL VARCHAR2(100)
, VIN VARCHAR2(17)
, XXGKBH VARCHAR2(29)
, SB VARCHAR2(100)
, SCCDZ VARCHAR2(100)
, SCDATE VARCHAR2(8)
, FDJH VARCHAR2(50)
, FDJSB VARCHAR2(100)
, FDJSCCDZ VARCHAR2(100)
, SCCMC VARCHAR2(200)
, CREATIONTIME DATE
, CREATOR VARCHAR2(100)
, LASTMODIFICATIONTIME DATE
, LASTMODIFIER VARCHAR2(100)
, DELETIONTIME DATE
, ISDELETED NUMBER(1)
, DELETER VARCHAR2(100)
, CONSTRAINT IF_EM_WQPF_1_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

insert into IF_EM_WQPF_1 (ID,VEHICLEMODEL,VIN,XXGKBH,SB,SCCDZ,SCDATE,FDJH,FDJSB,FDJSCCDZ,SCCMC,CREATIONTIME,CREATOR,LASTMODIFICATIONTIME,LASTMODIFIER,DELETIONTIME,ISDELETED,DELETER) values(
    SEQ_EM_WQPF_ID.Next(),
    'CAR',
    'testvincode012345',
    '01234567890123456789012345678',
    'SH',
    '上海市宝山区长逸路188号1115室',
    '20191022',
    'XXXYYYY',
    'ZZZZ',
    'DDDDD',
    'ISUZU',
    to_date('20191022','yyyymmdd'),
    'SH',
    to_date('20191022','yyyymmdd'),
    '',
    to_date('20191022','yyyymmdd'),
    '0',
    '');

drop table IF_EM_WQPF_2;
CREATE TABLE IF_EM_WQPF_2
(
  ID NUMBER(8) NOT NULL
, WQPF_ID NUMBER(8) NOT NULL
, RH NUMBER(4,2)
, ET NUMBER(5,2)
, AP NUMBER(5,2)
, CREATIONTIME DATE
, CREATOR VARCHAR2(100)
, LASTMODIFICATIONTIME DATE
, LASTMODIFIER VARCHAR2(100)
, DELETIONTIME DATE
, ISDELETED NUMBER(1)
, DELETER VARCHAR2(100)
, CONSTRAINT IF_EM_WQPF_2_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

drop table IF_EM_WQPF_3;
CREATE TABLE IF_EM_WQPF_3
(
  ID NUMBER(8) NOT NULL
, WQPF_ID NUMBER(8) NOT NULL
, TESTTYPE NUMBER(1)
, TESTNO VARCHAR2(18)
, TESTDATE VARCHAR2(8)
, APASS NUMBER(1)
, OPASS NUMBER(1)
, OTESTDATE VARCHAR2(8)
, EPASS NUMBER(1)
, RESULT NUMBER(1)
, CREATIONTIME DATE
, CREATOR VARCHAR2(100)
, LASTMODIFICATIONTIME DATE
, LASTMODIFIER VARCHAR2(100)
, DELETIONTIME DATE
, ISDELETED NUMBER(1)
, DELETER VARCHAR2(100)
, CONSTRAINT IF_EM_WQPF_3_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

drop table IF_EM_WQPF_4;
CREATE TABLE IF_EM_WQPF_4
(
  ID NUMBER(8) NOT NULL
, WQPF_ID NUMBER(8) NOT NULL
, OBD VARCHAR2(2)
, ODO NUMBER(8,1)
, CREATIONTIME DATE
, CREATOR VARCHAR2(100)
, LASTMODIFICATIONTIME DATE
, LASTMODIFIER VARCHAR2(100)
, DELETIONTIME DATE
, ISDELETED NUMBER(1)
, DELETER VARCHAR2(100)
, CONSTRAINT IF_EM_WQPF_4_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

drop table IF_EM_WQPF_4_A;
CREATE TABLE IF_EM_WQPF_4_A
(
  ID NUMBER(8) NOT NULL
, WQPF_ID NUMBER(8) NOT NULL
, WQPF4_ID NUMBER(8) NOT NULL
, MODULEID VARCHAR2(11)
, CALID VARCHAR2(20)
, CVN VARCHAR2(20)
, CREATIONTIME DATE
, CREATOR VARCHAR2(100)
, LASTMODIFICATIONTIME DATE
, LASTMODIFIER VARCHAR2(100)
, DELETIONTIME DATE
, ISDELETED NUMBER(1)
, DELETER VARCHAR2(100)
, CONSTRAINT IF_EM_WQPF_4_A_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

drop table IF_EM_WQPF_5_1;
CREATE TABLE IF_EM_WQPF_5_1
(
  ID NUMBER(8) NOT NULL
, WQPF_ID NUMBER(8) NOT NULL
, REAC NUMBER(3,2)
, LEACMAX NUMBER(3,2)
, LEACMIN NUMBER(3,2)
, LRCO NUMBER(3,2)
, LLCO NUMBER(3,2)
, LRHC NUMBER(4)
, LLHC NUMBER(4)
, HRCO NUMBER(3,2)
, HLCO NUMBER(3,2)
, HRHC NUMBER(4)
, HLHC NUMBER(4)
, CREATIONTIME DATE
, CREATOR VARCHAR2(100)
, LASTMODIFICATIONTIME DATE
, LASTMODIFIER VARCHAR2(100)
, DELETIONTIME DATE
, ISDELETED NUMBER(1)
, DELETER VARCHAR2(100)
, CONSTRAINT IF_EM_WQPF_5_1_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

drop table IF_EM_WQPF_5_2;
CREATE TABLE IF_EM_WQPF_5_2
(
  ID NUMBER(8) NOT NULL
, WQPF_ID NUMBER(8) NOT NULL
, ARHC5025 NUMBER(4)
, ALHC5025 NUMBER(4)
, ARCO5025 NUMBER(3,2)
, ALCO5025 NUMBER(3,2)
, ARNOX5025 NUMBER(4)
, ALNOX5025 NUMBER(4)
, ARHC2540 NUMBER(4)
, ALHC2540 NUMBER(4)
, ARCO2540 NUMBER(3,2)
, ALCO2540 NUMBER(3,2)
, ARNOX2540 NUMBER(4)
, ALNOX2540 NUMBER(4)
, CREATIONTIME DATE
, CREATOR VARCHAR2(100)
, LASTMODIFICATIONTIME DATE
, LASTMODIFIER VARCHAR2(100)
, DELETIONTIME DATE
, ISDELETED NUMBER(1)
, DELETER VARCHAR2(100)
, CONSTRAINT IF_EM_WQPF_5_2_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

drop table IF_EM_WQPF_5_3;
CREATE TABLE IF_EM_WQPF_5_3
(
  ID NUMBER(8) NOT NULL
, WQPF_ID NUMBER(8) NOT NULL
, VRHC NUMBER(3,1)
, VLHC NUMBER(2,1)
, VRCO NUMBER(2,1)
, VLCO NUMBER(2,1)
, VRNOX NUMBER(2,1)
, VLNOX NUMBER(2,1)
, CREATIONTIME DATE
, CREATOR VARCHAR2(100)
, LASTMODIFICATIONTIME DATE
, LASTMODIFIER VARCHAR2(100)
, DELETIONTIME DATE
, ISDELETED NUMBER(1)
, DELETER VARCHAR2(100)
, CONSTRAINT IF_EM_WQPF_5_3_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

drop table IF_EM_WQPF_5_4;
CREATE TABLE IF_EM_WQPF_5_4
(
  ID NUMBER(8) NOT NULL
, WQPF_ID NUMBER(8) NOT NULL
, RATEREVUP NUMBER(5)
, RATEREVDOWN NUMBER(5)
, REV100 NUMBER(5)
, MAXPOWER NUMBER(4,1)
, MAXPOWERLIMIT NUMBER(4,1)
, SMOKE100 NUMBER(3,2)
, SMOKE80 NUMBER(3,2)
, SMOKELIMIT NUMBER(3,2)
, NOX NUMBER(4)
, NOXLIMIT NUMBER(4)
, CREATIONTIME DATE
, CREATOR VARCHAR2(100)
, LASTMODIFICATIONTIME DATE
, LASTMODIFIER VARCHAR2(100)
, DELETIONTIME DATE
, ISDELETED NUMBER(1)
, DELETER VARCHAR2(100)
, CONSTRAINT IF_EM_WQPF_5_4_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

drop table IF_EM_WQPF_5_5;
CREATE TABLE IF_EM_WQPF_5_5
(
  ID NUMBER(8) NOT NULL
, WQPF_ID NUMBER(8) NOT NULL
, RATEREV NUMBER(5)
, REV NUMBER(5)
, SMOKEK1 NUMBER(3,2)
, SMOKEK2 NUMBER(3,2)
, SMOKEK3 NUMBER(3,2)
, SMOKEAVG NUMBER(3,2)
, SMOKEKLIMIT NUMBER(3,2)
, CREATIONTIME DATE
, CREATOR VARCHAR2(100)
, LASTMODIFICATIONTIME DATE
, LASTMODIFIER VARCHAR2(100)
, DELETIONTIME DATE
, ISDELETED NUMBER(1)
, DELETER VARCHAR2(100)
, CONSTRAINT IF_EM_WQPF_5_5_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

drop table IF_EM_WQPF_5_6;
CREATE TABLE IF_EM_WQPF_5_6
(
  ID NUMBER(8) NOT NULL
, WQPF_ID NUMBER(8) NOT NULL
, VRCO NUMBER(5)
, VLCO NUMBER(5)
, VRHCNOX NUMBER(3,2)
, VLHCNOX NUMBER(3,2)
, CREATIONTIME DATE
, CREATOR VARCHAR2(100)
, LASTMODIFICATIONTIME DATE
, LASTMODIFIER VARCHAR2(100)
, DELETIONTIME DATE
, ISDELETED NUMBER(1)
, DELETER VARCHAR2(100)
, CONSTRAINT IF_EM_WQPF_5_6_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);

drop table IF_EM_WQPF_6;
CREATE TABLE IF_EM_WQPF_6
(
  ID NUMBER(8) NOT NULL
, WQPF_ID NUMBER(8) NOT NULL
, ANALYMANUF VARCHAR2(30)
, ANALYNAME VARCHAR2(30)
, ANALYMODEL VARCHAR2(50)
, ANALYDATE VARCHAR2(8)
, DYNOMODEL VARCHAR2(50)
, DYNOMANUF VARCHAR2(50)
, CREATIONTIME DATE
, CREATOR VARCHAR2(100)
, LASTMODIFICATIONTIME DATE
, LASTMODIFIER VARCHAR2(100)
, DELETIONTIME DATE
, ISDELETED NUMBER(1)
, DELETER VARCHAR2(100)
, CONSTRAINT IF_EM_WQPF_6_PK PRIMARY KEY
  (
    ID
  )
  ENABLE
);
